main:main.cpp Object.o Splash.o
	g++ main.cpp Object.o Splash.o -o main
Object.o:Object.cpp Object.h Splash.h
	g++ -c Object.cpp -o Object.o 
Splash.o:Splash.cpp Splash.h
	g++ -c Splash.cpp -o Splash.o